"""image

Revision ID: 38deef8a03ed
Revises: f08b9eb19b89
Create Date: 2025-03-06 15:43:53.201635

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '38deef8a03ed'
down_revision: Union[str, None] = 'f08b9eb19b89'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('question_images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('image', sa.String(length=1024), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_question_images_id'), 'question_images', ['id'], unique=False)
    op.drop_constraint('user_progress_exams_fkey', 'user_progress', type_='foreignkey')
    op.drop_column('user_progress', 'exams')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_progress', sa.Column('exams', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('user_progress_exams_fkey', 'user_progress', 'exams', ['exams'], ['id'])
    op.drop_index(op.f('ix_question_images_id'), table_name='question_images')
    op.drop_table('question_images')
    # ### end Alembic commands ###
