"""exam2

Revision ID: f08b9eb19b89
Revises: 2cf37504ce16
Create Date: 2025-02-25 15:54:38.137958

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f08b9eb19b89'
down_revision: Union[str, None] = '2cf37504ce16'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_progress', sa.Column('exams', sa.Integer(), default=0))
    op.create_foreign_key(None, 'user_progress', 'exams', ['exams'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_progress', type_='foreignkey')
    op.drop_column('user_progress', 'exams')
    # ### end Alembic commands ###
